name: Gh-Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Only works with v2
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          workingDir: example
          webRenderer: canvaskit
          targetBranch: with-example-web-export
          baseHref: /square-progress-indicator/
